-- Create new user (schema)
CREATE USER WAREHOUSE_MANAGEMENT IDENTIFIED BY 1234;

-- Grant permissions to connect and create basic objects to new users
GRANT CONNECT, RESOURCE TO WAREHOUSE_MANAGEMENT;

-- Grant permissions to tablespaces users
ALTER USER WAREHOUSE_MANAGEMENT QUOTA UNLIMITED ON USERS;

-- Alter session to WAREHOUSE_MANAGEMENT
ALTER SESSION SET current_schema = WAREHOUSE_MANAGEMENT;

-- Create WAREHOUSE table
CREATE TABLE WAREHOUSE (
    WarehouseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WarehouseName VARCHAR2(50) NOT NULL
);

-- Tạo bảng Products
CREATE TABLE PRODUCT (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductName VARCHAR2(100) NOT NULL
);

-- Tạo bảng Attributes
CREATE TABLE ATTRIBUTE (
    AttributeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SizeAttribute NUMBER NOT NULL,
    TypeAttribute VARCHAR2(100) NOT NULL,
    ColorAttribute VARCHAR2(100) NOT NULL,
    BrandAttribute VARCHAR2(100) NOT NULL,
	ProductID NUMBER NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- Create USER table
CREATE TABLE USERS (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserName VARCHAR2(100) NOT NULL,
    Password VARCHAR2(100) NOT NULL,
    RoleID NUMBER(1) NOT NULL,
    WarehouseID NUMBER NULL,
    FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE(WarehouseID)
);

-- Create WAREHOUSE_PRODUCT table
CREATE TABLE WAREHOUSE_PRODUCT (
    WarehouseID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    PRIMARY KEY (WarehouseID, ProductID),
    FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE(WarehouseID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- Create example warehouses
INSERT INTO WAREHOUSE (WarehouseName) VALUES ('Warehouse A');
INSERT INTO WAREHOUSE (WarehouseName) VALUES ('Warehouse B');
INSERT INTO WAREHOUSE (WarehouseName) VALUES ('Warehouse C');

-- Create example users and admins
INSERT INTO USERS (UserName, Password, RoleID, WarehouseID) VALUES ('admin1', 'YWRtaW4x', 0, NULL); 
INSERT INTO USERS (UserName, Password, RoleID, WarehouseID) VALUES ('admin2', 'YWRtaW4y', 0, NULL); 

INSERT INTO USERS (UserName, Password, RoleID, WarehouseID) VALUES ('user1', 'dXNlcjE=', 1, 1); 
INSERT INTO USERS (UserName, Password, RoleID, WarehouseID) VALUES ('user2', 'dXNlcjI=', 1, 2);  
INSERT INTO USERS (UserName, Password, RoleID, WarehouseID) VALUES ('user3', 'dXNlcjM=', 1, 3); 

