-- Create new user (schema)
CREATE USER WAREHOUSE_MANAGEMENT_2 IDENTIFIED BY 1234;

-- Grant permissions to connect and create basic objects to new users
GRANT CONNECT, RESOURCE TO WAREHOUSE_MANAGEMENT_2;

-- Grant permissions to tablespaces users
ALTER USER WAREHOUSE_MANAGEMENT_2 QUOTA UNLIMITED ON USERS;

-- Alter session to WAREHOUSE_MANAGEMENT
ALTER SESSION SET current_schema = WAREHOUSE_MANAGEMENT_2;

-- Create TBL_USERS table
CREATE TABLE TBL_USERS 
(
  ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
  USERNAME VARCHAR2(50) NOT NULL,
  PASSWORD VARCHAR2(50) NOT NULL,
  ROLE_ID INT NOT NULL,
  WAREHOUSE_ID INT,
  CREATED_BY INT,
  CREATED_DATE DATE DEFAULT SYSDATE,
  UPDATED_BY INT,
  UPDATED_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT TBL_USERS_PK PRIMARY KEY (ID)
);

-- Create TBL_ROLES table
CREATE TABLE TBL_ROLES 
(
  ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
  ROLE_NAME VARCHAR2(50) NOT NULL,
  CONSTRAINT TBL_ROLES_PK PRIMARY KEY (ID)
);

-- Create TBL_WAREHOUSES table
CREATE TABLE TBL_WAREHOUSES
(
  ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  ADDRESS VARCHAR2(100),
  CREATED_BY INT,
  CREATED_DATE DATE DEFAULT SYSDATE,
  UPDATED_BY INT,
  UPDATED_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT TBL_WAREHOUSES_PK PRIMARY KEY (ID)
);

-- Create TBL_PRODUCTS table
CREATE TABLE TBL_PRODUCTS
(
  ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
  WAREHOUSE_ID INT NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(200),
  QUANTITY INT,
  PRICE DECIMAL(10, 2),
  CREATED_BY INT,
  CREATED_DATE DATE DEFAULT SYSDATE,
  UPDATED_BY INT,
  UPDATED_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT TBL_PRODUCTS_PK PRIMARY KEY (ID),
  CONSTRAINT TBL_PRODUCTS_WAREHOUSE_FK FOREIGN KEY (WAREHOUSE_ID) REFERENCES TBL_WAREHOUSES(ID)
);

-- Create ATTRIBUTE table
CREATE TABLE ATTRIBUTE (
    ID INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    SIZE_ATTRIBUTE NUMBER NOT NULL,
    TYPE_ATTRIBUTE VARCHAR2(100) NOT NULL,
    COLOR_ATTRIBUTE VARCHAR2(100) NOT NULL,
    BRAND_ATTRIBUTE VARCHAR2(100) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CONSTRAINT ATTRIBUTE_PK PRIMARY KEY (ID),
    CONSTRAINT ATTRIBUTE_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES TBL_PRODUCTS(ID)
);

-- Insert example data into TBL_ROLES
--INSERT INTO TBL_ROLES (ROLE_NAME) VALUES ('Admin');
--INSERT INTO TBL_ROLES (ROLE_NAME) VALUES ('User');
--
-- Insert example data into TBL_WAREHOUSES
--INSERT INTO TBL_WAREHOUSES (NAME, ADDRESS, CREATED_BY) VALUES ('Warehouse A', 'Address A', 1);
--INSERT INTO TBL_WAREHOUSES (NAME, ADDRESS, CREATED_BY) VALUES ('Warehouse B', 'Address B', 1);
--INSERT INTO TBL_WAREHOUSES (NAME, ADDRESS, CREATED_BY) VALUES ('Warehouse C', 'Address C', 1);
--
-- Insert example data into TBL_USERS
--INSERT INTO TBL_USERS (USERNAME, PASSWORD, ROLE_ID, WAREHOUSE_ID, CREATED_BY) VALUES ('admin1', 'YWRtaW4x', 1, NULL, 1);
--INSERT INTO TBL_USERS (USERNAME, PASSWORD, ROLE_ID, WAREHOUSE_ID, CREATED_BY) VALUES ('admin2', 'YWRtaW4y', 1, NULL, 1);
--INSERT INTO TBL_USERS (USERNAME, PASSWORD, ROLE_ID, WAREHOUSE_ID, CREATED_BY) VALUES ('user1', 'dXNlcjE=', 2, 1, 1);
--INSERT INTO TBL_USERS (USERNAME, PASSWORD, ROLE_ID, WAREHOUSE_ID, CREATED_BY) VALUES ('user2', 'dXNlcjI=', 2, 2, 1);
--INSERT INTO TBL_USERS (USERNAME, PASSWORD, ROLE_ID, WAREHOUSE_ID, CREATED_BY) VALUES ('user3', 'dXNlcjM=', 2, 3, 1);